### ISSUE TITLE
no recording

### ISSUE THREAD

**Issue by martinschonger** [noamtcohen/AudioStreamer#1]
hi, when I click on start recording on the client side just creates an empty wav-file on the server side. I have installed the two required modules but I am not that experienced with node.js.. what could I possibly do wrong? thanks

**Comment by noamtcohen** [comment]
Hi Martin,
I've only tested this on a Mac, what are you using? When you run the server do you see any output in the console? Is the wav  file zero bytes or just recording silence? Please also look at the js console on the client, what browser are you using? I only tested on chrome. 
N.

**Comment by martinschonger** [comment]
Hi Noam,

thank you for the fast response!

I’m using Win8.1 64bit. Yes it says “new connection…” and “Stream Start”. When I try to open the wav-File it says that there is just metadata (it’s 44 bytes and 0 “bytes on disk”). How do I view the js console on the client? I’m using the latest version of chrome.

Martin

**Comment by noamtcohen** [comment]
Hi Martin, 
On chrome you can right click and choose "inspect element" you should have a console tab in that small window. 
Are you seeing the visuals of the recording signal in the browser window? When you click start recording chrome should ask you if you permit to use the microphone, did you permit?
N.

**Comment by martinschonger** [comment]
Ok I opened console tab now:

I don’t see any visuals of the recording in the browser window and don’t get asked to permit using my mic.

The error seen above already exists before I click on “Start Recording”.

Martin

**Comment by martinschonger** [comment]
sorry it didn't take the img: http://s28.postimg.org/xikr0hq59/err.png

**Comment by noamtcohen** [comment]
I've open this issue a while ago with binaryjs: https://github.com/binaryjs/binaryjs/issues/73.
Still this should not be the problem. I think the issue is that you are not opening index.html from an http server but from the local file system. 
Try to install this: https://www.npmjs.com/package/simplehttpserver and run it from another terminal window in the directory of index.html and then browser to http://localhost:8000/.
You should now get this window in chrome and it should work: http://postimg.org/image/6a5fynfj9/

Martin, its a bit late here, please let me know who it gos and I'll try to get back to you tomorrow.

**Comment by martinschonger** [comment]
I've installed simplehttpserver now and started it with index.html, but as soon as I open http://localhost:8000/ I get this http://s11.postimg.org/ridu3jaw3/err2.png error in cmd..

**Comment by noamtcohen** [comment]
What do you see in the browser?

**Comment by martinschonger** [comment]
nothing.. it just keeps loading

**Comment by noamtcohen** [comment]
So you see the audio streamer screen in the browser?
Ignore the log from the simple http server and start the streamer server from another terminal and start recording.

**Comment by martinschonger** [comment]
no, I can't access the audio streamer via localhost:8000

**Comment by noamtcohen** [comment]
I've updated server.js, please download and see new instructions (i've add connect static server):  https://github.com/noamtcohen/AudioStreamer/blob/master/README.md

**Comment by martinschonger** [comment]
thank you.. I'll try it as soon as possible :)

**Comment by noamtcohen** [comment]
Hi Martin, I was wandering if you took a look at the change I made for you to see if it works.

**Comment by martinschonger** [comment]
Hi again, I tried it today and got this error http://s13.postimg.org/xcq97r8xz/err3.png after clicking the Start-button. I have to mention that I still had to open index.html by double-clicking it instead of accessing localhost:8000.

**Comment by noamtcohen** [comment]
Hi, it will not work by double clicking the index file, you have to open it from a local server, please create the folder "recordings" in the root directory of the application and make sure it has write permissions.
Did you download the new version with the local web server? what happens when you open http://localhost:8080/index.html in the browser window? The port should be 8080 not 8000
