### ISSUE TITLE
Max record time

### ISSUE THREAD

**Issue by jwdeitch** [noamtcohen/AudioStreamer#4]
noamtcohen, thanks for this great project! I would like to know though, is there anyway to set a max record length time / file size on the server side js? 

Thanks

**Comment by noamtcohen** [comment]
I think it would be relatively easy, instead of piping the data, you could listen to the data even on the source stream,  count the bytes and write them to the destination stream. When the count reaches the limit, you close the streams. Look at line 26 in server.js

```
stream.pipe(fileWriter);
```

could be changed to:

```
  var limit = 1024;
  var byteCount =0;
  stream.on("data",function(data){
        fileWriter.write(data);
        byteCount += data.length;
        if(byteCount>limit){
              stream.end();
              fileWriter.end();
        }
  });
```

or something like that....
